version: '3'

services:
    notebook:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        volumes:
            - ./notebooks:/notebooks
        ports:
            - '8888:8888'
            - '4040:4040'